services:
  - type: web
    name: telegram-gtin-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    runtime: python3
    pythonVersion: 3.11.7
